---
- name: cmk inventory
  command: cmk -II
  become: true
  become_user: "{{ omdistro_site }}"
  notify: cmk reload

- name: cmk reload
  become: true
  become_user: "{{ omdistro_site }}"
  command: cmk -O

- name: restart apache
  service: name={{ omdistro_apache_svc_name }} state=restarted

- name: restart omd
  service: name=omd state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart xinetd
  service: name=xinetd state=restarted
